### PR TITLE
add support for attach without mapParams and source simultaneously

### PR DESCRIPTION
**Pull request by sergeysova**
```ts
const originalFx = createEffect(() => {
  // your logic
})

const derivedFx = attach({ effect: originalFx })
```

inspired by: https://github.com/effector/patronum/issues/79

### CODE REVIEW

**Comment by doasync** [comment]
It doesn't attach anything, you will break naming

**Comment by sergeysova** [comment]
@doasync Do you have any suggestions?

**Comment by zerobias** [comment]
attach new effect to given one

**Comment by doasync** [comment]
> attach new effect to given one

Oh, well, then, yeah, okay

**Review by zerobias — APPROVED** [review]
Splendid pr, thanks!

**Pull request merged**
