### PR TITLE
useStore: return store state instead of react state

### PR DESCRIPTION
**Pull request by sergeysova**
fixes: https://codesandbox.io/s/y21jj6l8n9

### CODE REVIEW

**Comment by doasync** [comment]
@goodmind, may @sergeysova remove useStoreFast?

**Comment by doasync** [comment]
This PR should be named like 'useStore: return store state instead of react state'

**Comment by doasync** [comment]
If you merge with develop there will be an unused import

**Comment by zerobias** [comment]
big thanks! 👍👍

**Pull request merged**
