### PR TITLE
fix(effector): replace two handlers of inFlight with one

### PR DESCRIPTION
**Pull request by sergeysova**

### CODE REVIEW

**Comment by yumauri** [comment]
This could be breaking change, because this changes order of events, from

> `finally` → `done`/`fail` → `inFlight`

to

> `finally` → `inFlight` → `done`/`fail`

Looks like effector doesn't have tests for that case, but my tests in ReEffect will definitely need reconcideration :)

And to be clear:
I'm OK with this PR, just making point on changes.

**Comment by yumauri** [comment]
I thought a bit more, maybe I am wrong about order... `done`/`fail` remains first and second children of `finally`, and `inFlight` is added as third one, and this will not change order. Need to check explicitly.

**Comment by zerobias** [comment]
@yumauri 

> This could be breaking change, because this changes order of events, from
> 
> > `finally` → `done`/`fail` → `inFlight`
> 
> to
> 
> > `finally` → `inFlight` → `done`/`fail`

I added inFlight and pending to the [current execution order test](https://github.com/zerobias/effector/blob/master/src/effector/__tests__/effect/index.test.js#L271). Indeed, this PR will change execution order: `doneData` will be called after `inFlight 0`. Good that we didn't release `doneData` yet 🙃

**Comment by zerobias** [comment]
Nice catch, @sergeysova! I was overlooking that move

**Pull request merged**
