### PR TITLE
Small Effect changes

### PR DESCRIPTION
**Pull request by yumauri**
Main thing I want to change here → preserve _any_ fields in result in events `done` and `fail`.

I don't know if you are ok with destructuring assignment syntax, if no — feel free to reject or ask for changes :)

### CODE REVIEW

**Comment by yumauri** [comment]
Hm. I see some build issues...

**Comment by yumauri** [comment]
Changed to good old `delete`.
I don't really like `omitStatus` function, but what do you think about whole approach?

**Comment by yumauri** [comment]
I wanted to reuse these events in ReEffect :)
But I cannot in the current implementation, because data can contain field `strategy`, which is eliminated in `done`/`fail` after mapping :(

**Comment by yumauri** [comment]
I understand this is bold change of internal implementation in favor of external tool, so, I'm totally fine if you reject this approach. But it was worth trying :)

**Comment by yumauri** [comment]
Oh, thank you, I didn't pay attention, that stack contains previous values.

Returned mapping for `done`/`fail` event, what about other changes?

I removed bind for `onSettled`, because regular functions are more performant, that binded ones.

**Comment by yumauri** [comment]
Also I'm curious, why rename `finally` twice? Just to have name "finally" inside `onCopy`, corresponding with "finally" name of event?

image

**Comment by zerobias** [comment]
Could you show a difference in performance between binded and curried functions?

**Comment by zerobias** [comment]
Yes, finally in scope must match with name in onCopy array

**Comment by yumauri** [comment]
Unfortunately I'm not good at micro-benchmarking, but I was sure this is common knowledge. Maybe it is not so clear in the modern engines, but binded functions was definitely slower maybe few years ago. 

There are two benchmarks (not mine) for example, and results in my Safari right now:

https://jsperf.com/bind-vs-closure-2019

image

https://jsperf.com/partial-bind-closure

image

**Comment by zerobias** [comment]
Seems reasonable, thanks!

**Pull request merged**
