### PR TITLE
Fix sample duplication

### LINKED ISSUE #176: using sample leads to duplication in the outline
[Issuehunt badges](https://issuehunt.io/r/zerobias/effector/issues/176)

**Code to reproduce the issue:**

https://share.effector.dev/Y0ldDaVz

```js
const submit = createEvent()
const apiRequest = createEffect()
const form = createStore({user: 'alice'})

sample({
  source: form,
  clock: submit,
  target: apiRequest,
})
```

**Expected behavior:**

**Outline:**

Events
- submit
- apiRequest done
- apiRequest fail

Effects
- apiRequest

Storages
- form

**Actual behavior:**

**Outline:**

Events
- submit
- apiRequest done
- apiRequest fail
- apiRequest done
- apiRequest fail

Effects
- apiRequest
- apiRequest

Storages
- form

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $40.00)

- [issuehunt issuehunt](https://issuehunt.io/u/issuehunt) ($40.00)
### Submitted pull Requests
- [#178 Fix sample duplication](https://issuehunt.io/r/zerobias/effector/pull/178)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/zerobias/effector/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
---
IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>

### PR DESCRIPTION
**Pull request by abliarsar**
Fixes #176 
I'm not really sure about the way I create a name for the sample result. I saw function for creating unit names, but it's private and I don't know how to import that one in editor project.
@zerobias, tell me please, if I miss something

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Referenced issues

This pull request has been submitted to:
- [#176: using sample leads to duplication in the outline](https://issuehunt.io/repos/123197392/issues/176)
---

IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>

### CODE REVIEW

**Comment by goodmind** [comment]
Doesn't sample already have name?

**Comment by abliarsar** [comment]
True, but that name is not informative at all
It's just copying name of source
https://share.effector.dev/CwiZMY4R

**Comment by goodmind** [comment]
https://github.com/zerobias/effector/blob/master/src/effector/sample/sampler.js#L86

**Comment by abliarsar** [comment]
Now I think that naming changes was unnecessary, at least they should not be in that pull request.
I revert them for now, so there will be only fix of the duplication problem without any other changes.

**Comment by goodmind** [comment]
can you submit this PR to issuehunt.io/r/zerobias/effector

**Pull request merged**
